# [PackageDev] target_format: plist, ext: tmPreferences
scope: source.java
settings:
  bracketIndentNextLinePattern: ^\s*\b(if|while|else)\b[^;]*$|^\s*\b(for)\b.*$
  increaseIndentPattern: ^\s*(.*\{[^}]*|\b(case\s+\w+|default):)\s*$
  decreaseIndentPattern: ^\s*((.*\*/\s*)?\};?|\b(case\s+\w+|default):)\s*$
  unIndentedLinePattern: ^\s*((\*/|//|\*).*)?$
  indentSquareBrackets: true
  shellVariables:
  - name: TM_COMMENT_START
    value: '// '
  - name: TM_COMMENT_START_2
    value: '/*'
  - name: TM_COMMENT_END_2
    value: '*/'
