[tool.pylint."MESSAGE CONTROL"]
disable = [
    "missing-docstring",
    "line-too-long",
    "no-self-use",
    "subprocess-run-check",
    "too-few-public-methods",
    "too-many-instance-attributes"
]

[tool.isort]
profile = "black"
