# [PackageDev] target_format: plist, ext: tmPreferences
scope: source.java
settings:
  bracketIndentNextLinePattern: ^\s*\b(if|while|else)\b[^;]*$|^\s*\b(for)\b.*$
  increaseIndentPattern: ^\s*(.*\{[^}]*|\b(case\s+\w+|default):)\s*$
  decreaseIndentPattern: ^(.*\*/)?\s*\}.*$
  unIndentedLinePattern: ^\s*((\*/|//| \*).*)?$
  indentSquareBrackets: true
