# [PackageDev] target_format: plist, ext: tmPreferences
scope: source.c++
settings:
  bracketIndentNextLinePattern: ^\s*\b(if|while|else)\b[^;]*$|^\s*\b(for)\b.*$
  increaseIndentPattern: ^\s*(.*\{[^}]*|\b(case\s+\w+|default|public|private|protected):|/\*!.*)\s*$
  decreaseIndentPattern: ^\s*((.*\*/\s*)?\}.*|\b(case\s+\w+|default|public|private|protected):|\*/)\s*$
  indentSquareBrackets: true
