# [PackageDev] target_format: plist, ext: tmPreferences
scope: source.js
settings:
  bracketIndentNextLinePattern: ^\s*\b(if|while|else)\b[^;]*$|^\s*\b(for)\b.*$
  increaseIndentPattern: ^\s*(.*\{[^}]*|\b(case\s+\w+|default):)\s*$
  decreaseIndentPattern: ^(.*\*/)?\s*\}.*$
  unIndentedLinePattern: ^\s*((\*/|//| \*).*)?$
  cancelCompletion: ^\s*(function)\s*[a-zA-Z$_][\w$]+
  indentSquareBrackets: true
  icon: file_type_js
